In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import lib.clean
import lib.data_preprocessing as DP

# Extract the Data
df = pd.read_csv('Telco_Customer_Churn.csv')

# Data Cleaning
#print(df.isna().sum())

# Capitalize the column names
df = lib.clean.clean_dataframe(df)

df = lib.clean.group_tenure(df)

# Data Preprocessing
keep_columns = []
for col in df.columns:
    if col not in ['CreatedTenure', 'Customerid']:
        keep_columns.append(col)

df = df[keep_columns]

In [4]:
df.head()

Gender Seniorcitizen Partner Dependents  Tenure Phoneservice  \
0  Female            No     Yes         No       1           No   
1    Male            No      No         No      34          Yes   
2    Male            No      No         No       2          Yes   
3    Male            No      No         No      45           No   
4  Female            No      No         No       2          Yes   

      Multiplelines Internetservice Onlinesecurity Onlinebackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  Deviceprotection Techsupport Streamingtv Streamingmovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  Paperlessbilling              Paymentmethod  Monthlycharges  Totalcharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [76]:
encode = le.fit(df['Paymentmethod'])

In [79]:
sorted(df['Paymentmethod'].unique())

['Bank transfer (automatic)',
 'Credit card (automatic)',
 'Electronic check',
 'Mailed check']

In [78]:
encode.classes_

array(['Bank transfer (automatic)', 'Credit card (automatic)',
       'Electronic check', 'Mailed check'], dtype=object)

In [80]:
encode.transform(df['Paymentmethod'])

array([2, 3, 3, ..., 2, 3, 0])

In [82]:
list(encode.transform(df['Paymentmethod']))

[2,
 3,
 3,
 0,
 2,
 2,
 1,
 3,
 2,
 0,
 3,
 1,
 1,
 0,
 2,
 1,
 3,
 0,
 1,
 2,
 2,
 0,
 3,
 1,
 1,
 0,
 2,
 2,
 1,
 3,
 1,
 1,
 3,
 0,
 0,
 0,
 2,
 1,
 2,
 0,
 3,
 1,
 3,
 1,
 2,
 2,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 2,
 2,
 2,
 3,
 0,
 3,
 3,
 2,
 0,
 0,
 0,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 3,
 3,
 0,
 2,
 3,
 1,
 0,
 2,
 1,
 3,
 0,
 2,
 3,
 2,
 0,
 0,
 0,
 3,
 2,
 3,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 0,
 2,
 3,
 1,
 1,
 3,
 2,
 3,
 3,
 2,
 2,
 0,
 3,
 2,
 2,
 1,
 0,
 2,
 2,
 1,
 0,
 3,
 3,
 3,
 1,
 2,
 0,
 1,
 0,
 1,
 3,
 2,
 1,
 3,
 2,
 3,
 1,
 2,
 3,
 0,
 0,
 3,
 3,
 0,
 2,
 2,
 2,
 0,
 3,
 3,
 0,
 0,
 2,
 2,
 0,
 2,
 3,
 0,
 0,
 2,
 3,
 0,
 0,
 1,
 0,
 3,
 0,
 1,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 0,
 2,
 0,
 3,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 2,
 3,
 0,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 3,
 3,
 2,
 2,
 3,
 0,
 0,
 1,
 2,
 2,
 2,
 3,
 2,
 3,
 2,


In [83]:
encode.classes_

array(['Bank transfer (automatic)', 'Credit card (automatic)',
       'Electronic check', 'Mailed check'], dtype=object)

In [85]:
encode.transform(['Bank transfer (automatic)', 'Credit card (automatic)', 'Electronic check', 'Mailed check'])

array([0, 1, 2, 3], dtype=int64)

In [86]:
keys = encode.classes_.tolist()
values = sorted(encode.transform(keys).tolist())

In [87]:
values

[0, 1, 2, 3]

In [88]:
# creating a dictionary from 2 lists
payment_dict = dict(zip(keys, values))

In [89]:
payment_dict

{'Bank transfer (automatic)': 0,
 'Credit card (automatic)': 1,
 'Electronic check': 2,
 'Mailed check': 3}

In [161]:
import torch
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder

class Embedding:
    
    def __init__(self, lis, n_dim, column_name):
        self.lis = lis
        self.n_dim = n_dim
        self.le = LabelEncoder()
        self.column_name = column_name
        
    def create(self):
        encode = self.le.fit(self.lis)
        keys = encode.classes_.tolist()
        values = sorted(encode.transform(keys).tolist())
        lis_dict = dict(zip(keys, values))
        embeds = nn.Embedding(len(keys), self.n_dim)
        
        columns = []
        for i in range(self.n_dim):
            columns.append('{}{}{}'.format(self.column_name,'_', str(i)))
            
        df = pd.DataFrame()  
        df_dict = {}
        for key in self.lis:
            x = embeds(torch.tensor([lis_dict[key]], dtype=torch.long)).detach().numpy().tolist()
            for i in range(self.n_dim):
                df_dict[columns[i]] = x[0][i]
            df = df.append(df_dict, ignore_index = True)

        return df

In [162]:
emb = Embedding(df['Gender'], 5, 'Gender')

In [163]:
dfdf = emb.create()

['Gender_0', 'Gender_1', 'Gender_2', 'Gender_3', 'Gender_4']


In [164]:
dfdf

Gender_0  Gender_1  Gender_2  Gender_3  Gender_4
0     2.398197  1.634077  1.333532 -0.043158 -0.506483
1     0.577098 -1.551923 -1.730992  0.891119 -2.721003
2     0.577098 -1.551923 -1.730992  0.891119 -2.721003
3     0.577098 -1.551923 -1.730992  0.891119 -2.721003
4     2.398197  1.634077  1.333532 -0.043158 -0.506483
...        ...       ...       ...       ...       ...
7038  0.577098 -1.551923 -1.730992  0.891119 -2.721003
7039  2.398197  1.634077  1.333532 -0.043158 -0.506483
7040  2.398197  1.634077  1.333532 -0.043158 -0.506483
7041  0.577098 -1.551923 -1.730992  0.891119 -2.721003
7042  0.577098 -1.551923 -1.730992  0.891119 -2.721003

[7043 rows x 5 columns]

In [30]:
import torch
import torch.nn as nn

In [44]:
embeds = nn.Embedding(2, 2)  # 2 words in vocab, 5 dimensional embeddings


In [45]:
num3 = torch.tensor([1], dtype=torch.long)

In [46]:
embeds(num3)

tensor([[2.4336, 0.2111]], grad_fn=<EmbeddingBackward>)

In [41]:
embeds(num)

tensor([[-1.8700,  1.5761]], grad_fn=<EmbeddingBackward>)

In [42]:
num2 = torch.tensor([0], dtype=torch.long)

In [43]:
embeds(num2)

tensor([[0.5387, 0.8722]], grad_fn=<EmbeddingBackward>)

In [ ]:
lookup_tensor = torch.tensor([word_to_ix["hello"]], dtype=torch.long)
hello_embed = embeds(lookup_tensor)
print(hello_embed)

In [91]:
columns = []
for i in range(5):
    columns.append('{}{}'.format('Gender', str(i)))

In [92]:
columns

['Gender0', 'Gender1', 'Gender2', 'Gender3', 'Gender4']