In [2]:
# Pytorch
import torch
x = torch.rand(2, 3)

In [3]:
x / x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.div(x, x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
x = torch.rand(3, 5)

In [14]:
x[1, 2].item()

0.5119104981422424

In [15]:
x[1, 2]

tensor(0.5119)

In [17]:
x = torch.tensor([[2, 3, 4, 5], [1, 2, 3, 4], [0, 1, 3, 5]])

In [18]:
x

tensor([[2, 3, 4, 5],
        [1, 2, 3, 4],
        [0, 1, 3, 5]])

In [20]:
x.size()

torch.Size([3, 4])

In [25]:
x[2, 3].item() * 5

25

In [27]:
x @ x.T

tensor([[54, 40, 40],
        [40, 30, 31],
        [40, 31, 35]])

In [29]:
y = x.T @ x

In [38]:
y.view(2, 8)[1,1].item() - 21

0

In [32]:
y

tensor([[ 5,  8, 11, 14],
        [ 8, 14, 21, 28],
        [11, 21, 34, 47],
        [14, 28, 47, 66]])

In [40]:
x1 = torch.zeros(2, 4)
x2 = torch.ones(4, 2)
x3 = torch.rand(5, 5)
x4 = torch.tensor([[2.3, 4, 5, 1], [0, 0, 0, 0], [1, 2, 3, 4]])

In [41]:
x4

tensor([[2.3000, 4.0000, 5.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 2.0000, 3.0000, 4.0000]])

In [43]:
x1 + x1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
x2 + x2

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [46]:
torch.mul(x2, x2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [49]:
x2 @ x1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
x4 @ x4.T

tensor([[47.2900,  0.0000, 29.3000],
        [ 0.0000,  0.0000,  0.0000],
        [29.3000,  0.0000, 30.0000]])

In [53]:
x4.size()

torch.Size([3, 4])

In [54]:
x4.view(12)

tensor([2.3000, 4.0000, 5.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000,
        2.0000, 3.0000, 4.0000])

In [55]:
x4.view(4, 3)

tensor([[2.3000, 4.0000, 5.0000],
        [1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000],
        [2.0000, 3.0000, 4.0000]])

In [57]:
y = x4.view(2, 6)

In [58]:
y

tensor([[2.3000, 4.0000, 5.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 2.0000, 3.0000, 4.0000]])

In [59]:
y.size()

torch.Size([2, 6])

In [60]:
x4.view(-1, 2)

tensor([[2.3000, 4.0000],
        [5.0000, 1.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [1.0000, 2.0000],
        [3.0000, 4.0000]])

In [61]:
x4.view(2, -1)

tensor([[2.3000, 4.0000, 5.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 2.0000, 3.0000, 4.0000]])

In [63]:
x4.transpose(1, 2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [64]:
x4

tensor([[2.3000, 4.0000, 5.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 2.0000, 3.0000, 4.0000]])

In [70]:
x4.transpose(0, 1)

tensor([[2.3000, 0.0000, 1.0000],
        [4.0000, 0.0000, 2.0000],
        [5.0000, 0.0000, 3.0000],
        [1.0000, 0.0000, 4.0000]])

In [69]:
x4.T

tensor([[2.3000, 0.0000, 1.0000],
        [4.0000, 0.0000, 2.0000],
        [5.0000, 0.0000, 3.0000],
        [1.0000, 0.0000, 4.0000]])

In [71]:
-2 * torch.tensor([[1, 9, 6]])

tensor([[ -2, -18, -12]])

In [72]:
-2 * torch.tensor([1, 9, 6])

tensor([ -2, -18, -12])

In [73]:
torch.tensor([1, 9, 6]) * 1.5

tensor([ 1.5000, 13.5000,  9.0000])

In [74]:
torch.tensor([1, 9, 6]) * torch.tensor(1.5)

tensor([ 1.5000, 13.5000,  9.0000])

In [75]:
x = torch.tensor([-1, 2, 2])
y = torch.tensor([1, 0, -3])

In [77]:
(x.T @ y).item()

-7

In [78]:
y.T @ x

tensor(-7)

In [79]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [1, 2, 4]])

In [80]:
x.T @ y

tensor([[11, 16, 25],
        [19, 26, 38],
        [27, 36, 51]])

In [81]:
y.T @ x

tensor([[11, 19, 27],
        [16, 26, 36],
        [25, 38, 51]])

In [82]:
x * y

tensor([[ 7, 16, 27],
        [ 4, 10, 24]])

In [83]:
torch.mul(x, y)

tensor([[ 7, 16, 27],
        [ 4, 10, 24]])

In [84]:
-2 * (x.T @ y)

tensor([[ -22,  -32,  -50],
        [ -38,  -52,  -76],
        [ -54,  -72, -102]])

In [86]:
x.T @ (x + y)

tensor([[28, 38, 52],
        [41, 55, 74],
        [54, 72, 96]])

In [87]:
x.T @ x + x.T @ y

tensor([[28, 38, 52],
        [41, 55, 74],
        [54, 72, 96]])

In [94]:
one = torch.tensor([[1, 1, 1], [1, 1, 1]])

In [95]:
one.T @ x

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [98]:
torch.tensor([0, 0, 0, 0, 1, 0]).T @ x.view(6)

tensor(5)

In [99]:
one

tensor([[1, 1, 1],
        [1, 1, 1]])

In [100]:
one.view(6, 1)

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1]])

In [101]:
one.view(1, 6)

tensor([[1, 1, 1, 1, 1, 1]])

In [102]:
x4

tensor([[2.3000, 4.0000, 5.0000, 1.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 2.0000, 3.0000, 4.0000]])

In [106]:
x4.view(6, 2)

tensor([[2.3000, 4.0000],
        [5.0000, 1.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [1.0000, 2.0000],
        [3.0000, 4.0000]])

In [107]:
z = x.T @ y + 5

In [108]:
z

tensor([[16, 21, 30],
        [24, 31, 43],
        [32, 41, 56]])

In [109]:
x.T @ y

tensor([[11, 16, 25],
        [19, 26, 38],
        [27, 36, 51]])

In [112]:
xx = torch.tensor([2, 3, 4], dtype=float)

In [113]:
torch.norm(xx)

tensor(5.3852, dtype=torch.float64)

In [116]:
u = torch.tensor([1.8, 2.0, -3.7, 4.7])
v = torch.tensor([0.6, 2.1, 1.9, -1.4])
w = torch.tensor([2.0, 1.9, -4.0, 4.6])

In [117]:
torch.norm(u - v)

tensor(8.3678)

In [118]:
torch.norm(u - w)

tensor(0.3873)

In [120]:
torch.norm(v - w).item()

8.532877922058105

In [205]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.swapcase()

In [206]:
myCar = Car('ToYota', 'cAmRy', 2016)

In [207]:
myCar.get_descriptive_name()

'tOyOTA CaMrY 2016'

In [33]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper() 
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")

In [34]:
newCar = Car('benz', 'shopper', 2020)

In [35]:
newCar.odometer_reading

0

In [37]:
newCar.odometer_reading = 20000

In [38]:
newCar.odometer_reading

20000

In [39]:
newCar.get_descriptive_name()

'BENZ SHOPPER 2020'

In [40]:
newCar.make

'benz'

In [41]:
newCar.make = 'Camry'

In [42]:
newCar.make 

'Camry'

In [43]:
newCar.read_odometer()

This car has 20000 miles on it


In [44]:
newCar.get_descriptive_name()

'CAMRY SHOPPER 2020'

In [54]:
cars = ['Toyota', 'Benz', 'Omolewa', 'Davids']
inp = input('Please, Enter a name of a car: ')
if inp in cars:
    print('Good job')
else:
    print('Nay')

Please, Enter a name of a car: Dimeji
Nay


In [45]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper()
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")
    
    def update_odometer(self, mileage):
        """Set the odometer to a certain value"""
        self.odometer_reading = mileage

In [52]:
newCar = Car('toyota', 'camry', 2021)
newCar2 = Car('Nissan', 'Note', 2050)
newCar3 = Car('Omolewa', 'Adaramola', 'Davids')

In [50]:
newCar.make

'toyota'

In [51]:
newCar2.make

'Nissan'

In [47]:
newCar.update_odometer(50000)

In [48]:
newCar.odometer_reading

50000

In [229]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper()
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")
    
    def update_odometer(self, mileage):
        """
        Set the odometer to a certain value
        Reject the change if it attempts to roll back the odometer
        """
        if mileage >= self.odometer_reading:
            self.odometer_reading = mileage
        else:
            print("You can't roll back an odometer!")

In [56]:
myCar = Car('toyota', 'camry', 2030)

In [57]:
myCar.odometer_reading

0

In [58]:
myCar.odometer_reading = 300

In [59]:
myCar.odometer_reading

300

In [60]:
myCar.update_odometer(200)

You can't roll back an odometer!


In [61]:
myCar.update_odometer(2000)

In [62]:
myCar.odometer_reading

2000

In [63]:
myCar.update_odometer(1999)

You can't roll back an odometer!


In [230]:
class Car:
    """A simple attempt to represent a car"""
    carcar = 'Omolewa'
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper()
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")
    
    def update_odometer(self, mileage):
        """
        Set the odometer to a certain value
        Reject the change if it attempts to roll back the odometer
        """
        if mileage >= self.odometer_reading:
            self.odometer_reading = mileage
        else:
            print("You can't roll back an odometer!")
    
    def increment_odometer(self, miles):
        """Add the given amount to the odometer reading"""
        self.odometer_reading += miles

In [65]:
newCar = Car('subaru', 'outback', 2012)

In [66]:
newCar.odometer_reading

0

In [67]:
newCar.odometer_reading = 23445

In [68]:
newCar.odometer_reading

23445

In [69]:
newCar.read_odometer()

This car has 23445 miles on it


In [70]:
newCar.update_odometer(23000)

You can't roll back an odometer!


In [71]:
newCar.update_odometer(30000)

In [72]:
newCar.odometer_reading

30000

In [73]:
newCar.increment_odometer(10000)

In [74]:
newCar.odometer_reading

40000

## Inheritance

In [233]:
class ElectricCar(Car):
    """Represent aspects of a car, specific to electric vehicles."""
    
    def __init__(self, make, model, year, number, subject, grade):
        self.number = number
        """Initialize attribute of the parent class"""
        super().__init__(make, model, year)
        self.number = number
        self.subject = subject
        self.grade = grade
        self.numsub = number * subject
    
    def Dimeji(self, name):
        return self.number * name

In [234]:
shola = ElectricCar(make = 'T', model = 'M', year = 2020, number =2, subject = 'P', grade = 100)

In [235]:
shola.make

2

In [94]:
myElectric = ElectricCar('tesla', 'model s', 2019, 30)

In [95]:
myElectric.carcar

'Omolewa'

In [96]:
myElectric.Dimeji('Davids')

'DavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavidsDavids'

In [97]:
myElectric.odometer_reading

0

In [98]:
myElectric.update_odometer(25000)

In [99]:
myElectric.odometer_reading

25000

In [100]:
myElectric.update_odometer(20000)

You can't roll back an odometer!


In [101]:
class ElectricCar(Car):
    """Represent aspects of a car, specific to electric vehicles."""
    
    def __init__(self, make, model, year):
        """
        Initialize attribute of the parent class.
        then initialize the attribute specific to Electric Car
        """
        super().__init__(make, model, year)
        self.battery_size = 75
    
    def describe_battery(self):
        """Print a statement describing the battery size."""
        print(f"This car has a {self.battery_size}-kWh battery.")

In [102]:
myElectric = ElectricCar('Toyota', 'Camry', 2025)

In [103]:
myElectric.battery_size

75

In [104]:
myElectric.describe_battery()

This car has a 75-kWh battery.


### Overriding the Method from parent class

In [112]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make, model, year):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper()
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")
    
    def update_odometer(self, mileage):
        """
        Set the odometer to a certain value
        Reject the change if it attempts to roll back the odometer
        """
        if mileage >= self.odometer_reading:
            self.odometer_reading = mileage
        else:
            print("You can't roll back an odometer!")
    
    def increment_odometer(self, miles):
        """Add the given amount to the odometer reading"""
        self.odometer_reading += miles
    
    def fill_gas_tank(self):
        """Print Statement when the gas tank is low"""
        print(f"Your gas is low, fill the gas tank")

In [113]:
class ElectricCar(Car):
    """Represent aspects of a car, specific to electric vehicles."""
    
    def __init__(self, make, model, year):
        """
        Initialize attribute of the parent class.
        then initialize the attribute specific to Electric Car
        """
        super().__init__(make, model, year)
        self.battery_size = 75
    
    def describe_battery(self):
        """Print a statement describing the battery size."""
        print(f"This car has a {self.battery_size}-kWh battery.")
    
    def fill_gas_tank(self):
        """Electric car don't have gas tank"""
        print(f"This car doesn't need a gas tank")

In [114]:
myCar = Car('toyota', 'camry', 2024)
myElectric = ElectricCar('tesla', 'model s', 2023)

In [115]:
myCar.fill_gas_tank()

Your gas is low, fill the gas tank


In [116]:
myElectric.fill_gas_tank()

This car doesn't need a gas tank


### Instances as Attributes

In [238]:
class Battery:
    """A simple attempt to model a battery for an electric car"""
    
    def __init__(self, battery_size = 150):
        """Initialize the battery attribute"""
        self.battery_size2 = battery_size
    
    def describe_battery2(self):
        """Print a statement describing the battery"""
        print(f"This car has a {self.battery_size2}-kWh battery") 
    
    def get_range(self):
        """Print a statement about the range this battery provides"""
        if self.battery_size2 > 200:
            range = 260
        else:
            range = 315
        
        print(f"This car can go about {range} miles on a full charge ")

In [239]:
class ElectricCar(Car):
    """Represent aspects of a car, specific to electric vehicles."""
    
    def __init__(self, make, model, year):
        """
        Initialize attribute of the parent class.
        then initialize the attribute specific to Electric Car
        """
        super().__init__(make, model, year)
        self.battery_size = 75
        self.battery = Battery()
    
    def describe_battery(self):
        """Print a statement describing the battery size."""
        print(f"This car has a {self.battery_size}-kWh battery.")
    
    def fill_gas_tank(self):
        """Electric car don't have gas tank"""
        print(f"This car doesn't need a gas tank")

In [240]:
electric = ElectricCar('tesla', 'model s', 3030)

TypeError: __init__() missing 1 required positional argument: 'battery_size'

In [205]:
electric.battery.battery_size2

150

In [206]:
electric.battery.describe_battery2()

This car has a 150-kWh battery


In [207]:
electric.battery.battery_size2 = 20000

In [208]:
electric.battery.battery_size2

20000

In [209]:
electric.battery.describe_battery2()

This car has a 20000-kWh battery


In [210]:
electric.battery.get_range()

This car can go about 260 miles on a full charge 


### Inheritance from more than one class

In [127]:
class Inherit(Battery, ElectricCar):
    def __init__(self, name):
        super().__init__()
        self.nameName = name

In [128]:
i = Inherit('Omolewa')

In [ ]:
i.

In [131]:
class Kunle:
    def __init__(self, number, name = 'Omolewa'):
        self.name = name
        self.number = number

In [132]:
class Kunle:
    def __init__(self, name = 'Omolewa', number):
        self.name = name
        self.number = number

SyntaxError: non-default argument follows default argument (<ipython-input-132-458d04a38083>, line 2)

In [134]:
1.5 + 1.5 + 1.5

4.5

### Importing Classes

### ASSIGNMENT

* Make a class Die with one attribute called sides, which has a default value of 6. Write a method called **roll_die()** that prints a random number between 1 and the number of sides the die has. Makea 6-sided die and roll it 10 times. Make a 10-sided die and a 20-sided die. Roll each die 10 times

* Make a list or tuple containing a series of 10 numbers and five letters. Randomly select four numbers or letters from the list and print a message saying that any ticket matching these four numbers or letters wins a prize

* You can use a loop to see how hard it might be to win the the kind of lottery you just modelled. Make a list or tuple called **my_ticket**. Write a loop that keeps pulling numbers until your ticket wins. Print a message reporting how many times the loop had to run to give you a winning ticket.

* One excellent resource for exploring the Python standard library is a site called Python Module of the Week. Go to **http://pymotw.com/** and look at the table of contents. Find a module that looks interesting to you ane read about it, perhaps starting with the random module

In [264]:
numbers = [20, 13, 50, 70, 100]

In [53]:
names = ['Shayo', 'Ihuoma', 'Dimeji', 'Kunle', 'Omolewa']
output = {} # {0: 'Shayo', 1:'Ihuoma', 2: 'Kunle'}
for key, value, i in enumerate(names):
    output[key] = value

ValueError: not enough values to unpack (expected 3, got 2)

In [51]:
output

{0: 'Shayo', 1: 'Ihuoma', 2: 'Dimeji', 3: 'Kunle', 4: 'Omolewa'}

In [46]:
output = {} # key = 'shayo', value = UK
output['Shayo'] = 'UK'

In [48]:
output = {}
key = 'Omolewa'
value = 36
output[key] = value

In [49]:
output

{'Omolewa': 36}

In [47]:
output

{'Shayo': 'UK'}

In [3]:
index, entry = 0, 'Shayo'
index, entry = 1, 'Ihuoma'

In [4]:
a

(23, 10)

In [ ]:
tuple: is immutable

In [17]:
names1 = ('Omolewa', 'Bukola', 'Abdul')
names2 = ['Shayo', 'Ihuoma', 'Dimeji', 'Kunle', 'Omolewa']

In [28]:
names1 = list(names1)

In [29]:
names1

['Omolewa', 'Bukola', 'Abdul']

In [30]:
names1[0] = 'Shola'

In [32]:
names1

['Shola', 'Bukola', 'Abdul']

In [33]:
names1 = tuple(names1)

In [34]:
names1

('Shola', 'Bukola', 'Abdul')

In [35]:
# Assignment;
name = 'Shayo is a Man'

In [36]:
name = name.split()

In [37]:
name

['Shayo', 'is', 'a', 'Man']

In [38]:
name[-1] = 'boy'

In [39]:
name

['Shayo', 'is', 'a', 'boy']

In [43]:
'@'.join(name)

'Shayo@is@a@boy'

In [44]:
# name = 'Ihuoma'

In [45]:
name.split()

['Ihuoma']

In [10]:
names2[0] = 'Sayo'

In [16]:
name1, name2, name3 = ('Omolewa', 'Bukola', 'Abdul', 'Ihuoma')

ValueError: too many values to unpack (expected 3)

In [20]:
_, _, _, d, _ = names2

In [22]:
_

'Omolewa'

In [23]:
a = 3
a = 4

In [24]:
a

4

In [14]:
name1

'Omolewa'

In [12]:
names1[0] = 'Ihuoma'

TypeError: 'tuple' object does not support item assignment

In [25]:
name = 'Ihuoma'

In [26]:
name[-2]

'm'

In [27]:
name[-2] = 'M'

TypeError: 'str' object does not support item assignment

In [ ]:
name = 'IhuoMa'

In [6]:
type(names)

tuple

In [ ]:
names = ['Shayo', 'Ihuoma', 'Dimeji', 'Kunle', 'Omolewa']
for i in names:
    print(i.upper())

In [ ]:
name = 'Shayo'
name = 'Ihuoma'

In [269]:
output = {}
for index, number in enumerate(numbers):
    output[index] = number

In [270]:
output

{0: 20, 1: 13, 2: 50, 3: 70, 4: 100}

In [266]:
num = {}

In [267]:
num['Shayo'] = 200

In [268]:
num

{'Shayo': 200}

In [271]:
output.items()

dict_items([(0, 20), (1, 13), (2, 50), (3, 70), (4, 100)])

In [272]:
# Use enumerate method on output.items()

## Sets

In [54]:
name = {10, 20, 49, 20, 50, 70, 10}

In [55]:
name

{10, 20, 49, 50, 70}

In [56]:
type(name)

set

In [75]:
numbers = [12, 45, 12, 80, 40, 100, 75, 80, 40, 20, 70, 70, 90, 100, 12, 12, 12, 12]
n = set(numbers)

In [76]:
# Why the order is not maintained (set in python)
for num in n:
    print(numbers.count(num))

2
2
2
1
6
1
2
1
1


In [74]:
set(numbers)

{12, 20, 40, 45, 70, 75, 80, 90, 100}

In [62]:
number.count(12)

4

In [278]:
# count the  number of occurence (frequency) of each entry in  list numbers: return a dictionary
# {12: 2, 45: 1}

In [286]:
output = {}
for num in set(numbers):
    print(num, numbers.count(num))
    #output[num] = numbers.count(num)

100 2
70 2
40 2
75 1
12 2
45 1
80 2
20 1
90 1


In [288]:
[numbers.count(num) for num in set(numbers)]

[2, 2, 2, 1, 2, 1, 2, 1, 1]

In [289]:
{num:numbers.count(num) for num in set(numbers)}

{100: 2, 70: 2, 40: 2, 75: 1, 12: 2, 45: 1, 80: 2, 20: 1, 90: 1}

In [281]:
output

{12: 2, 45: 1, 80: 2, 40: 2, 100: 2, 75: 1, 20: 1, 70: 2, 90: 1}

In [283]:
omolewa = {12: 2, 45: 1, 80: 2, 40: 2, 100: 2, 75: 1, 20: 1, 70: 2, 90: 1}

In [284]:
omolewa[12] = 100

In [285]:
omolewa

{12: 100, 45: 1, 80: 2, 40: 2, 100: 2, 75: 1, 20: 1, 70: 2, 90: 1}

In [292]:
def square(x):
    if x % 3 == 0:
        return x**2
    else:
        pass # silent
    

In [295]:
numbers = [10, 25, 34, 12, 45, 12, 80, 40, 100, 75, 80, 40, 20, 70, 70, 90, 100]
for num in (numbers):
    print(square(num))

144
2025
144
None
None
None
5625
None
None
None
None
None
8100
None


In [308]:
def square(x):
    for num in x:
        #print(num)
        if num % 3 != 0:
            print(num)
            return ('Hey')
        else:
            break
   

In [314]:
numbers = [10, 25, 34, 12, 45, 12, 80, 40, 100, 75, 80, 40, 20, 70, 70, 90, 100]

In [317]:
def square(x):
    for num in x:
        #print(num)
        if num % 3 != 0:
            print(num)
            return ('Hey')
        else:
            return(3)
            break
        print('Omolewa')

In [318]:
square(numbers)

10


'Hey'

## Files and Exceptions

Page 182

### Reading from entire file

In [79]:
with open('new.txt') as file_object:
    contents = file_object.read()
print(contents)

Eventually, Soong capitulated, but not before Lore had secretly contacted the Crystalline Entity in a bid for revenge, offering it the planet's life to ensure his own survival. After deactivating and dismantling Lore, Soong set about constructing Lore's brother, Data, an android without destabilizing emotions. (TNG: "Datalore", "Brothers", "Silicon Avatar", "The Offspring")

Lore's positronic net differed from Data's: it had a Type-"L" phase discriminator compared to Data's Type-"R". (TNG: "Time's Arrow")

Soong placed Lore's components into storage, intending to eventually correct Lore's behavioral problems. Lore later harbored resentment towards his creator for abandoning him. Yet, when he met his father again on Terlina III and learned that Soong was dying, he was sincerely upset and, for a brief moment, he displayed a genuine concern for his father. Nevertheless, Lore's malevolent streak soon prevailed.


In [321]:
#contents.split()

In [215]:
#print(contents.rstrip())

3.1415926535
  8979323846
  2643383279


### Reading line by line

In [80]:
filename = 'new.txt'

with open(filename) as file_object:
    for line in file_object:
        print(line)

Eventually, Soong capitulated, but not before Lore had secretly contacted the Crystalline Entity in a bid for revenge, offering it the planet's life to ensure his own survival. After deactivating and dismantling Lore, Soong set about constructing Lore's brother, Data, an android without destabilizing emotions. (TNG: "Datalore", "Brothers", "Silicon Avatar", "The Offspring")



Lore's positronic net differed from Data's: it had a Type-"L" phase discriminator compared to Data's Type-"R". (TNG: "Time's Arrow")



Soong placed Lore's components into storage, intending to eventually correct Lore's behavioral problems. Lore later harbored resentment towards his creator for abandoning him. Yet, when he met his father again on Terlina III and learned that Soong was dying, he was sincerely upset and, for a brief moment, he displayed a genuine concern for his father. Nevertheless, Lore's malevolent streak soon prevailed.


In [217]:
filename = 'pi_digits.txt'

with open(filename) as file_object:
    for line in file_object:
        print(line.rstrip())

3.1415926535
  8979323846
  2643383279


#### Making a list of lines from a file

In [218]:
with open(filename) as file_object:
    lines = file_object.readlines()

In [220]:
for line in lines:
    print(line.rstrip())

3.1415926535
  8979323846
  2643383279


In [221]:
lines

['3.1415926535\n', '  8979323846\n', '  2643383279']

In [222]:
pi_string = ''
for line in lines:
    pi_string += line.rstrip()

In [223]:
print(pi_string)

3.1415926535  8979323846  2643383279


In [224]:
pi_string = ''
for line in lines:
    pi_string += line.strip()

print(pi_string)

3.141592653589793238462643383279


## Writing to a file

In [89]:
text = 'My name is Bukola Omolewa and I love Cats and Dogs AND i AM IN SAME CLASS WITH eBONY'
filename = 'ihuoma.txt'

with open(filename, 'w') as file_object:
    file_object.write(text)

In [90]:
text = '\noMOLEWA My name is sHAYO'
filename = 'ihuoma.txt'

with open(filename, 'a') as file_object:
    file_object.write(text)

In [327]:
text2 = '\tAlso am a Machine Learning Engineer and Deep Learning Engineer'

with open(filename, 'a') as file_object:
    file_object.write(text2)

# Exceptions

In [228]:
print(5/0)

ZeroDivisionError: division by zero

### Using try-except block

In [229]:
try:
    print(5/0)
except ZeroDivisionError:
    print("You can't divide by zero")

You can't divide by zero


### Using Exceptions to prevent crashes

In [230]:
print('Give me only two numbers and I will divide them')
print("Enter 'q' to quit")

while True:
    fnum = input("\nFirst number: ")
    if fnum == 'q':
        break
    snum = input("Second number: ")
    if snum == 'q':
        break
    answer = int(fnum) / int(snum)
    
    print(answer)

Give me only two numbers nd I will divide them
Enter 'q' to quit

First number: 23
Second number: 5
4.6

First number: 30
Second number: 5
6.0

First number: 20
Second number: 0


ZeroDivisionError: division by zero

In [231]:
print('Give me only two numbers and I will divide them')
print("Enter 'q' to quit")

while True:
    fnum = input("\nFirst number: ")
    if fnum == 'q':
        break
    snum = input("Second number: ")
    if snum == 'q':
        break
    
    try:
        answer = int(fnum) / int(snum)
    except ZeroDivisionError:
        print("You can't divide by 0")
    else:
        print(answer)

Give me only two numbers and I will divide them
Enter 'q' to quit

First number: 0
Second number: 2
0.0

First number: 7
Second number: 0
You can't divide by 0

First number: q


In [244]:
with open('school.txt') as file_object:
    contents = file_object.read()
print(contents)

FileNotFoundError: [Errno 2] No such file or directory: 'school.txt'

In [245]:
filename = 'school.txt'

try:
    with open(filename, encoding = 'utf-8') as f:
        contents = f.read()
except FileNotFoundError:
    print(f'Sorry, the file {filename} does not exist')
else:
    words = contents.split()
    count = len(words)
    print(f"There are {count} words in the {filename}")

Sorry, the file school.txt does not exist


In [239]:
#Lets create a function to count words

def word_count(filename):
    """Count the approximate number of words in a file"""
    try:
        with open(filename, encoding = 'utf-8') as f:
            contents = f.read()
    except FileNotFoundError:
        print(f'Sorry, the file {filename} does not exist')
    else:
        words = contents.split()
        count = len(words)
        print(f"There are {count} words in the {filename}")

In [240]:
word_count(filename)

There are 17842 words in the alice.txt


In [241]:
word_count('omolewa.txt')

Sorry, the file omolewa.txt does not exist


### Working with multiple files

In [242]:
filenames = ['little_women.txt', 'siddhartha.txt', 'omolewa.txt', 'alice.txt']

In [243]:
for filename in filenames:
    word_count(filename)

There are 189092 words in the little_women.txt
There are 46296 words in the siddhartha.txt
Sorry, the file omolewa.txt does not exist
There are 17842 words in the alice.txt


# Storing Data

### Using json.dump() and json.load()

In [246]:
import json

In [248]:
numbers = [2, 4, 6, 1, 10, 50, 1000, 'Akeem', 'Shola']

filename = 'Akeem.json'

with open(filename, 'w') as f:
    json.dump(numbers, f)

In [249]:
with open(filename) as f:
    contents = json.load(f)

In [250]:
contents

[2, 4, 6, 1, 10, 50, 1000, 'Akeem', 'Shola']

# Unit Testing

### Testing a function

In [248]:
def get_formated_name(first, last):
    """Generate neatly formatted full name"""
    full_name = f"{first} {last}"
    return full_name.title()

In [250]:
get_formated_name('omolewa', 'adaramola')

'Omolewa Adaramola'

In [251]:
import unittest

In [254]:
class NameTestCase(unittest.TestCase):
    """Test for get_formated_name"""
    
    def test_first_last_name(self):
        """Do the name like 'Adaramola Bukola' works"""
        formated_name = get_formated_name('Omolewa', 'Adaramola')
        self.assertEqual(formated_name, 'Omolewa Adaramola')

In [256]:
unittest.main() # refactor

E
ERROR: C:\Users\user\AppData\Roaming\jupyter\runtime\kernel-f8e495e9-dd1f-4f99-ae5f-b872533cbf0f (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'C:\Users\user\AppData\Roaming\jupyter\runtime\kernel-f8e495e9-dd1f-4f99-ae5f-b872533cbf0f'

----------------------------------------------------------------------
Ran 1 test in 0.042s

FAILED (errors=1)


SystemExit: True

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [255]:
if __name__ == '__main__':
    unittest.main()

E
ERROR: C:\Users\user\AppData\Roaming\jupyter\runtime\kernel-f8e495e9-dd1f-4f99-ae5f-b872533cbf0f (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'C:\Users\user\AppData\Roaming\jupyter\runtime\kernel-f8e495e9-dd1f-4f99-ae5f-b872533cbf0f'

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (errors=1)


SystemExit: True

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [257]:
import pandas as pd

In [258]:
data = pd.read_csv('http://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_master.csv')

In [259]:
data.head()

hpi_type     hpi_flavor frequency                   level  \
0  traditional  purchase-only   monthly  USA or Census Division   
1  traditional  purchase-only   monthly  USA or Census Division   
2  traditional  purchase-only   monthly  USA or Census Division   
3  traditional  purchase-only   monthly  USA or Census Division   
4  traditional  purchase-only   monthly  USA or Census Division   

                    place_name place_id    yr  period  index_nsa  index_sa  
0  East North Central Division   DV_ENC  1991       1     100.00    100.00  
1  East North Central Division   DV_ENC  1991       2     101.01    101.08  
2  East North Central Division   DV_ENC  1991       3     101.35    100.97  
3  East North Central Division   DV_ENC  1991       4     101.75    101.04  
4  East North Central Division   DV_ENC  1991       5     102.39    101.44

In [260]:
import flask

In [264]:
from multiprocessing import Pool

In [265]:
def f(x):
    return x*x

In [ ]:
if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))

In [139]:
f"my name is {'Omolewa'} {'Adaramola'}"

'my name is Omolewa Adaramola'

In [140]:
print('my name is' + ' ' + 'Adaramola')

my name is Adaramola


In [141]:
names = ['Omolewa', 'Abdul', 'Seun', 'Shola']

In [144]:
for name in names:
    print(f"the name of people in my class are {name}")

the name of people in my class are Omolewa
the name of people in my class are Abdul
the name of people in my class are Seun
the name of people in my class are Shola


In [148]:
for name in names:
    print('the name of people in my class are {} and {} is a boy'.format(name, name))

the name of people in my class are Omolewa and Omolewa is a boy
the name of people in my class are Abdul and Abdul is a boy
the name of people in my class are Seun and Seun is a boy
the name of people in my class are Shola and Shola is a boy


In [151]:
for name in names:
    if name.lower() != 'seun':
        print('the name of people in my class are', name, 'and', name, 'is a boy')
    else:
        print('the name of people in my class are', name, 'and', name, 'is a girl')

the name of people in my class are Omolewa and Omolewa is a boy
the name of people in my class are Abdul and Abdul is a boy
the name of people in my class are Seun and Seun is a girl
the name of people in my class are Shola and Shola is a boy


In [152]:
students = {'Name': ['Omolewa', 'Abdul', 'Seun', 'Shola', 'Akeem'],
           'Gender': ['male', 'male', 'male', 'female', 'male'],
           'Age': ['42', '56', '32', '54', 40]}

In [160]:
import pandas as pd
df = pd.DataFrame(students)

In [161]:
df

Name  Gender Age
0  Omolewa    male  42
1    Abdul    male  56
2     Seun    male  32
3    Shola  female  54
4    Akeem    male  40

In [164]:
df['Gender'][2] = 'female'

In [165]:
df

Name  Gender Age
0  Omolewa    male  42
1    Abdul    male  56
2     Seun  female  32
3    Shola  female  54
4    Akeem    male  40

In [168]:
df.iloc[3]['Gender'] = 'male'

In [169]:
df

Name  Gender Age
0  Omolewa    male  42
1    Abdul    male  56
2     Seun  female  32
3    Shola    male  54
4    Akeem    male  40

In [175]:
df.loc[(df['Name'] == 'Seun') & (df['Gender'] == 'female')]

Name  Gender Age
2  Seun  female  32

In [178]:
df

Name  Gender Age
0  Omolewa    male  42
1    Abdul    male  56
2     Seun  female  32
3    Shola    male  54
4    Akeem    male  40

In [179]:
df['Gender'] = df['Gender'].map(lambda x : x.capitalize())

In [180]:
df

Name  Gender Age
0  Omolewa    Male  42
1    Abdul    Male  56
2     Seun  Female  32
3    Shola    Male  54
4    Akeem    Male  40

In [190]:
df['Merge'] = df['Name'] + ' ' + df['Gender']

In [191]:
df

Name  Gender   Age         Merge
0  Omolewa    Male  42.0  Omolewa Male
1    Abdul    Male  56.0    Abdul Male
2     Seun  Female  32.0   Seun Female
3    Shola    Male  54.0    Shola Male
4    Akeem    Male  40.0    Akeem Male

In [192]:
df['Age'] = df['Age'].astype(float)

In [193]:
df

Name  Gender   Age         Merge
0  Omolewa    Male  42.0  Omolewa Male
1    Abdul    Male  56.0    Abdul Male
2     Seun  Female  32.0   Seun Female
3    Shola    Male  54.0    Shola Male
4    Akeem    Male  40.0    Akeem Male

In [219]:
class Car:
    """A simple attempt to represent a car"""
    
    def __init__(self, make = 'Benz', model = 'C 240', year = 2018):
        """Initialize attributes to describe a car"""
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        """Return a neatly formatted descriptive name"""
        long_name = f"{self.make} {self.model} {self.year}"
        return long_name.upper()
    
    def read_odometer(self):
        """Print a statement showing car Milage"""
        print(f"This car has {self.odometer_reading} miles on it")
    
    def update_odometer(self, mileage):
        """Set the odometer to a certain value"""
        self.odometer_reading = mileage
    
    def update_model(self, model):
        self.model = model
        
    def update_make(self, make):
        self.make = make

In [220]:
SholaCar = Car()

In [221]:
SholaCar.model = 

'C 240'

In [222]:
SholaCar.update_model('Camry')

In [223]:
SholaCar.model

'Camry'

In [218]:
SholaCar.make = 'Toyota'
SholaCar.model = 'Camry'
SholaCar.year = 2021
SholaCar.odometer_reading = 100000

In [212]:
SholaCar.update_odometer(50000)

In [213]:
SholaCar.odometer_reading

50000

In [251]:
!pip install pytest

You should consider upgrading via the 'c:\users\owner\anaconda3\python.exe -m pip install --upgrade pip' command.


In [252]:
import random

In [254]:
random.randint(1, 10)

7

In [91]:
def div(n, m):
    return n / m

In [92]:
div(4, 2)

2.0

In [93]:
div(4, 0)

ZeroDivisionError: division by zero

In [344]:
def div1(n, m):
   
        return  n / m
    

In [101]:
def div2(n, m):
    try:
        output = n / m
    except ZeroDivisionError:
        pass
    else:
        return output

In [102]:
div2(4, 0)

In [100]:
l = div2(4, 0)
print('Omolewa' * 5)

OmolewaOmolewaOmolewaOmolewaOmolewa


In [351]:
def factorial(n):
    try:
        if n == 0 or n == 1:
            output = 1
        else:
            output = (n * factorial(n - 1))
    except RecursionError:
        print('Running for ever')
    else:
        return output

In [352]:
factorial(4)

24

In [353]:
factorial(-4)

Running for ever


TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [354]:
# Numpy and Pandas DataFrame

In [103]:
import torch

In [104]:
import torch.nn as nn

In [ ]:
nn.Embedding

In [108]:
import requests